# Generated by Django 4.2.11 on 2025-05-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouzamapdata',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('mouza_id', models.IntegerField()),
                ('mouza_name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField()),
                ('jl_number', models.CharField(max_length=20)),
                ('division_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(max_length=100)),
                ('upazila_name', models.CharField(max_length=100)),
                ('survey_id', models.IntegerField()),
                ('mutation_survey_id', models.IntegerField(blank=True, null=True)),
                ('survey_name', models.CharField(max_length=100)),
                ('survey_name_en', models.CharField(max_length=100)),
                ('mutation_survey_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mutation_survey_name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Mouza Map Data',
                'verbose_name_plural': 'Mouza Map Data',
            },
            bases=('globalapp.common',),
        ),
    ]
