# Generated by Django 4.2.11 on 2025-05-24 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('driveapp', '0002_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=255)),
                ('division_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driveapp.division')),
            ],
            bases=('globalapp.common',),
        ),
    ]
