# Generated by Django 4.2.11 on 2025-05-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('driveapp', '0003_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='District2',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('bbs_code', models.CharField(max_length=10)),
                ('district_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Division2',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('bbs_code', models.CharField(max_length=10, unique=True)),
                ('division_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('lams_id', models.IntegerField()),
                ('is_circle', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('bbs_code', models.CharField(max_length=10)),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_districts', to='driveapp.district2')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='district2',
            name='division_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='driveapp.division2'),
        ),
    ]
