# Generated by Django 4.2.11 on 2025-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0004_district2_division2_subdistrict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdistrict',
            name='lams_id',
            field=models.IntegerField(null=True),
        ),
    ]
