# Generated by Django 4.2.11 on 2025-05-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0005_alter_subdistrict_lams_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouzamapdata',
            name='district_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouzas', to='driveapp.district2'),
        ),
        migrations.AddField(
            model_name='mouzamapdata',
            name='division_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouzas', to='driveapp.division2'),
        ),
        migrations.AddField(
            model_name='mouzamapdata',
            name='subdistrict_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouzas', to='driveapp.subdistrict'),
        ),
    ]
