# Generated by Django 4.2.11 on 2025-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epspayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epstransaction',
            name='order_type',
            field=models.CharField(choices=[('file', 'File Purchase'), ('package', 'Package Purchase')], default='file', help_text='Type of purchase: file or package', max_length=20),
        ),
    ]
