# Generated by Django 4.2.11 on 2025-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_banneritem_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
