# Generated by Django 4.2.11 on 2025-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='daily_order_limit',
            field=models.IntegerField(default=0, help_text='Daily order limit (0 means unlimited)'),
        ),
    ]
