# Generated by Django 4.2.11 on 2025-10-09 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_daily_order_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('orders_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='packages.userpackage')),
            ],
            options={
                'verbose_name': 'Daily Order Usage',
                'verbose_name_plural': 'Daily Order Usage',
                'ordering': ['-date'],
                'unique_together': {('user_package', 'date')},
            },
        ),
    ]
