# Generated by Django 4.2.11 on 2025-10-13 18:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_dailyorderusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTypePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('SA_RS', 'SA/RS Survey'), ('CS', 'CS Survey'), ('BS', 'BS Survey'), ('SA', 'SA Survey'), ('RS', 'RS Survey')], help_text='Survey type identifier', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Display name in Bengali/English', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per file', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey Type Pricing',
                'verbose_name_plural': 'Survey Type Pricing',
                'ordering': ['sort_order', 'survey_type'],
            },
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
    ]
