# Generated by Django 4.2.11 on 2025-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_surveytypepricing_alter_userpackage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytypepricing',
            name='survey_type',
            field=models.CharField(choices=[('SA_RS', 'SA/RS Survey'), ('CS', 'CS Survey'), ('BS', 'BS Survey'), ('SA', 'SA Survey'), ('RS', 'RS Survey'), ('DIYARA', 'DIYARA Survey'), ('RS_BS', 'RS/BS Survey'), ('BS_RS', 'BS/RS Survey'), ('CS_SA', 'CS/SA Survey'), ('SA_CS', 'SA/CS Survey')], help_text='Survey type identifier', max_length=20, unique=True),
        ),
    ]
