# Generated by Django 4.2.11 on 2025-05-20 12:39

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('field_name', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='package_icons/')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('price_per_file', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file_limit', models.PositiveIntegerField(help_text='Maximum number of files allowed')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('video_url', models.URLField(help_text='YouTube video URL')),
                ('pro', models.ManyToManyField(related_name='packages_pro', to='others.packageitem')),
                ('regular', models.ManyToManyField(related_name='packages_regular', to='others.packageitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
