# Generated by Django 4.2.11 on 2025-05-20 14:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('video_url', models.URLField(help_text='Enter a valid YouTube video URL')),
            ],
            bases=('globalapp.common',),
        ),
    ]
