# Generated by Django 4.2.11 on 2025-05-30 17:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globalapp', '0014_basebeneficariesmodel'),
        ('others', '0002_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bKash Config', max_length=100)),
                ('sandbox', models.BooleanField(default=True, help_text='Enable sandbox mode for testing')),
                ('app_key', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bKash Configuration',
            },
        ),
        migrations.CreateModel(
            name='ExtraFeature',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('whatsapp_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid WhatsApp number in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('file_name', models.JSONField(blank=True, default=list)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('number', models.CharField(blank=True, help_text='Transaction or reference number', max_length=100, null=True)),
                ('extra_features', models.ManyToManyField(blank=True, null=True, related_name='purchases', to='others.extrafeature')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.packageitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('globalapp.common',),
        ),
    ]
