# Generated by Django 4.2.11 on 2025-06-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_bkashconfiguration_extrafeature_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='number',
            new_name='trx_number',
        ),
    ]
