# Generated by Django 4.2.11 on 2025-06-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_rename_number_purchases_trx_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitem',
            name='file_range',
            field=models.CharField(blank=True, help_text='Range of files this package item covers (e.g. 1-50, All, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='is_static',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package_type',
            field=models.CharField(blank=True, choices=[('bangladesh', 'Bangladesh'), ('division', 'Division'), ('district', 'District'), ('subdistrict', 'Subdistrict'), ('survey', 'Survey Type')], help_text='Type of package item', max_length=20, null=True),
        ),
    ]
