# Generated by Django 4.2.11 on 2025-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_packageitem_file_range_packageitem_is_static_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UddoktapayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
