# Generated by Django 4.2.11 on 2025-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_uddoktapayconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('others', 'Others')], default='bkash', max_length=20),
        ),
    ]
