# Generated by Django 4.2.11 on 2025-08-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('others', '0007_purchases_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='extrafeature',
            name='additionals',
            field=models.ManyToManyField(blank=True, related_name='extra_features', to='others.additional'),
        ),
    ]
