# Generated by Django 4.2.11 on 2025-08-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_additional_extrafeature_additionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
