# Generated by Django 4.2.11 on 2025-08-24 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_purchases_delivery_address_purchases_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid WhatsApp number in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
