# Generated by Django 4.2.11 on 2025-10-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_purchases_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('eps', 'EPS'), ('others', 'Others')], default='bkash', max_length=20),
        ),
    ]
