# Generated by Django 4.2.11 on 2025-10-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_alter_purchases_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('eps', 'EPS'), ('free', 'Free Order'), ('others', 'Others')], default='bkash', max_length=20),
        ),
    ]
